name: Continuous Integration
on: [ push, pull_request ]
jobs:
  build:
    name: Build Plugin
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: .\Tools\DistributionTool.exe -b -i "Sources\com.distrust.wakatime.sdPlugin" -o .
      - uses: actions/upload-artifact@v2
        with:
          name: plugin-artifact
          path: .\com.distrust.wakatime.streamDeckPlugin
  release:
    name: Publish Plugin in Release
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/download-artifact@v2
        with:
          name: plugin-artifact
          path: ${{runner.temp}}/artifacts
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: ${{runner.temp}}/artifacts
      - name: Create Release-Draft
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          draft: true
      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ${{runner.temp}}/artifacts/com.distrust.wakatime.streamDeckPlugin
          asset_name: com.distrust.wakatime.streamDeckPlugin
          asset_content_type: application/octet-stream
