name: Continuous Integration
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Build Plugin
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: .\Tools\DistributionTool.exe -b -i "Sources\com.distrust.wakatime.sdPlugin" -o .
      - uses: actions/upload-artifact@v2
        with:
          name: plugin-artifact
          path: .\com.distrust.wakatime.streamDeckPlugin
  release:
    name: Publish Plugin in Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      if: ${{ startsWith(github.ref, 'refs/tags/') }}
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "plugin-artifact"
          token: ${{ secrets.RELEASE_TOKEN }}
